### ISSUE TITLE
关于punk对应的ann benchmarks测试的一系列问题

### ISSUE THREAD

**Issue by Autumn1998** [baidu/puck#11]
最近尝试使用puck进行ann- benchmarks测试，有以下问题：

- 在build dockerfile之前，进行pip install requirements的时候，经常出现错误，主要集中在“无法找到package对应的版本”，不知道是不是版本问题，在这一步我没有安装成功的库选择了跳过，可能会导致后面的问题

- 在dockerfile中需要进行requirements的构建，但是经常出现“无法找到package对应的版本”的问题，后通过注释dockerfile中的

```
RUN pip3 config set global.index-url http://pip.baidu.com/root/baidu/+simple/
RUN pip3 config set global.index http://pip.baidu.com/root/baidu/
RUN pip3 config set global.trusted-host pip.baidu.com
``` 
后成功构建image，不知是因为我所在机构的封锁，还是链接问题

- 使用create database脚本进行download数据集之后会出现assert不通过的问题， 定位到代码是 ann- benchmarks / benchmark / darasets.py里面315行左右，是一个先assert在赋值。
![25a5df4a6c1fe8acfc7ad6bd6f7922b0](https://github.com/baidu/puck/assets/30105323/21288534-59f2-46a7-843d-14ca4b80964b)

- 使用run .py，通过镜像进行benchmark操作的时候，出现权限问题。该问题没有引起程序的崩溃。
![0d77d7567a28d3d154393e4fb59d008d](https://github.com/baidu/puck/assets/30105323/25c92659-a0e2-43b4-a112-7817d3ecb616)

- 最后程序崩贵在log的地方，指示为将dict作为real number输出
![fe841cc4109b663d7033cee0a6d11f41](https://github.com/baidu/puck/assets/30105323/fa64974a-968f-48e9-913c-5f997458ba51)

此外，在修改搜索的线程数的时候，需要修改CPU_LIMIT，但是我好像没有找到参数文件中的位置，所以直接进入代码中修改的。总之我没有能够完整的运行benchmark

**Comment by nk2014yj** [comment]
1.pip源的问题：dockerfile里设置了国内的源，如果下载有问题，可以试试其他的，不影响生成的docker镜像。
2.数据下载的问题：已修改代码，辛苦拉取最新的代码。
3.执行算法镜像，是root权限。data和result目录在本地和镜像内是同步的，辛苦检查docker镜像启动的账号，是否在本地目录下面有写权限。
4.log信息不全，暂时无法定位。辛苦解决3之后，看下这个问题是否解决。

**Comment by Autumn1998** [comment]
由于公司的权限管理，我无法在/usr一类的目录中执行写操作，请问如何手动执行写操作的路径？  我的理解是可以在挂载的数据盘上写入应该是可以做到的

**Comment by nk2014yj** [comment]
执行benchmark不需要root权限，需要你自己的账号在docker的用户组。
创建镜像时候，会安装库到/usr下，是镜像的/usr，非本地的，没有本地root也没关系。

**Comment by Autumn1998** [comment]
在puck测试中出现
<img width="1038" alt="image" src="https://github.com/baidu/puck/assets/30105323/d6797f3e-229d-4fc7-8a75-1cb14da4fc7b">
，是否是image的原因？

此外，该问题疑似造成在解析结果的时候出现
<img width="1535" alt="image" src="https://github.com/baidu/puck/assets/30105323/e978ccb4-b5d9-4ef5-808b-4682ebfaa8ab">

**Comment by heaoxiang** [comment]
> 在puck测试中出现 <img alt="image" width="1038" src="https://user-images.githubusercontent.com/30105323/274840323-d6797f3e-229d-4fc7-8a75-1cb14da4fc7b.png"> ，是否是image的原因？
> 
> 此外，该问题疑似造成在解析结果的时候出现 <img alt="image" width="1535" src="https://user-images.githubusercontent.com/30105323/274840550-e978ccb4-b5d9-4ef5-808b-4682ebfaa8ab.png">

程序没有正确退出，图1的报错可以具体一些吗？

**Comment by Autumn1998** [comment]
<img width="797" alt="image" src="https://github.com/baidu/puck/assets/30105323/388b91a5-6dfd-4651-99bf-4635aaa8ccc2">
<img width="773" alt="image" src="https://github.com/baidu/puck/assets/30105323/ffa19b7e-72ff-4fd4-8fc6-b4e8e348fb47">

**Comment by nk2014yj** [comment]
最近这个问题没有更新，我这边先关闭问题了。如果有新的使用问题，可以提新的issue，谢谢。
