### ISSUE TITLE
条件查询，后续有开源计划吗？

### ISSUE THREAD

**Issue by xuqiang** [baidu/puck#8]
条件查询：支持检索过程中的条件查询，从底层索引检索过程中就过滤掉不符合要求的结果，解决多路召回归并经常遇到的截断问题，更好满足组合检索的要求(暂未开源)

请问下，条件查询后续有开源计划吗？

**Comment by jy02414216** [comment]
> 条件查询：支持检索过程中的条件查询，从底层索引检索过程中就过滤掉不符合要求的结果，解决多路召回归并经常遇到的截断问题，更好满足组合检索的要求(暂未开源)
> 
> 请问下，条件查询后续有开源计划吗？

会开源，时间暂时未确定，初步计划可能会在年底
